---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: pierreb24/my-python3-numpy:latest
  commands:
  # install and init stuffs
    - make init
  # test
    - make test
    - make lint