dist: trusty

language: python

python:
  - 3.6

git:
  depth: 1

install:
  - pip3 install --upgrade pip
  - nvm install node
  - pip3 install pip-tools

script:
  - nvm use node
  - make init
  - make test
  - make lint