"""remove block

Revision ID: 1723494407
Revises: 1723410891
Create Date: 2024-08-12 22:26:47.499780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1723494407'
down_revision = '1723410891'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('block')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'block',
        sa.Column('text', sa.TEXT(), nullable=False),
        sa.Column('attributes', sa.TEXT(), nullable=True),
        sa.Column('order', sa.INTEGER(), nullable=False),
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('date_created', sa.DATETIME(), nullable=True),
        sa.Column('date_modified', sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
