"""choice is back

Revision ID: 1723319933
Revises: 88c7a6ccef29
Create Date: 2024-08-10 21:58:53.225085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1723319933'
down_revision = '88c7a6ccef29'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), default=1))
        batch_op.alter_column('position', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_entry', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
