"""add summary

Revision ID: 1723403409
Revises: 1723325823
Create Date: 2024-08-11 21:10:09.989540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1723403409'
down_revision = '1723325823'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brief', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), default=''))
        batch_op.alter_column('summary', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brief', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
