"""add visible to category

Revision ID: 1723407615
Revises: 1723403409
Create Date: 2024-08-11 22:20:15.173986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1723407615'
down_revision = '1723403409'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible', sa.Boolean(), default=True))
        batch_op.alter_column('visible', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('visible')

    # ### end Alembic commands ###
