"""summary

Revision ID: 1731087850
Revises: 1723494407
Create Date: 2024-11-08 18:44:10.653982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1731087850'
down_revision = '1723494407'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True, default=''))
        batch_op.alter_column('summary', nullable=False)

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True, default=''))
        batch_op.alter_column('summary', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_column('summary')

    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
