"""Add Album and Picture

Revision ID: 88c7a6ccef29
Revises: aae11ed4ed1c
Create Date: 2022-08-07 22:41:13.548709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c7a6ccef29'
down_revision = 'aae11ed4ed1c'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'album',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date_created', sa.DateTime(), nullable=True),
        sa.Column('date_modified', sa.DateTime(), nullable=True),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('slug', sa.VARCHAR(length=150), nullable=False),
        sa.Column('thumbnail_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['thumbnail_id'], ['picture.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'picture',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date_created', sa.DateTime(), nullable=True),
        sa.Column('date_modified', sa.DateTime(), nullable=True),
        sa.Column('date_taken', sa.DateTime(), nullable=True),
        sa.Column('picture_name', sa.VARCHAR(length=150), nullable=False),
        sa.Column('picture_thumb_name', sa.VARCHAR(length=150), nullable=False),
        sa.Column('picture_size', sa.Integer(), nullable=True),
        sa.Column('album_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picture')
    op.drop_table('album')
    # ### end Alembic commands ###
